[project]
name = "ai-game"
description = ""
authors = [
    {name=""}
]

requires-python = ">=3.10"
version = "0.0.1"
dynamic = ["dependencies"] # ["version"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
ai_game = "app.main:main"
